services:
  clive:
    image: ghcr.io/mangosango/clive:latest
    volumes:
      - /path/to/db_and_logs_folder:/config
    # environment:
    #   NODE_ENV: production
    #   LOG_LEVEL: error
    #   DISCORD_WEBHOOK_URL: https://discordapp.com/api/webhooks/YOUR_DISCORD/WEBHOOK_URL_HERE
    #   TWITCH_CHANNELS: "a_twitch_channel another_twitch_channel"
    #   TWITCH_CLIENT_ID: <twitch_client_id>
    #   TWITCH_CLIENT_SECRET: <twitch_client_secret>
    #   RESTRICT_CHANNELS: true
    #   MODS_ONLY: false
    #   SUBS_ONLY: false
    #   BROADCASTER_ONLY: false
    #   RICH_EMBED: true
    #   URL_AVATAR: http://i.imgur.com/9s3TBNv.png
    #   BOT_USERNAME: "Clive"
    # env_file: .env      # Alternatly use a .env file
